from ast_nodes import *
from inline import parse_inline
import html
from typing import Callable
import re

_macro_registry: dict[str, Callable[[Macro], str]] = {}

def register_macro(name: str):
    def deco(fn: Callable[[Macro], str]):
        _macro_registry[name] = fn
        return fn
    return deco


@register_macro("note")
def render_note(node: Macro) -> str:
    inner = parse_inline(node.content)
    return f'<div class="note">{inner}</div>'

@register_macro("center")
def render_center(node: Macro) -> str:
    inner = parse_inline(node.content)
    return f'<div style="text-align:center;">{inner}</div>'

@register_macro("box")
def render_box(node: Macro) -> str:
    cls = html.escape(node.attrs.get("type", ""))
    title = html.escape(node.attrs.get("title", ""))
    title_html = f'<div class="box-title">{title}</div>' if title else ''
    inner = parse_inline(node.content)
    return f'<div class="box {cls}">{title_html}<div class="box-content">{inner}</div></div>'

@register_macro("chart")
def render_chart(node: Macro) -> str:
    try:
        chart_type = html.escape(node.attrs.get("type", ""))
        title = html.escape(node.attrs.get("title", ""))
        title_html = f'<div class="chart-title">{title}</div>' if title else ''

        rows = []
        for line in node.content.split('\n'):
            line = line.strip()
            if line.startswith('|') and '|' in line[1:]:
                cells = [c.strip() for c in line.split('|') if c.strip()]
                if len(cells) >= 2:
                    rows.append(cells)

        if chart_type == "pie":
            chart_html = render_pie_chart(rows)
        elif chart_type == "bar":
            chart_html = render_bar_chart(rows)
        else:
            chart_html = "<div class='chart-error'>Unsupported chart type</div>"
        return f'<div class="chart {chart_type}">{title_html}{chart_html}</div>'
    except Exception as e:
        f'<div>Error creating chart, please check syntax!</div>'
    

def render_pie_chart(rows):
    try:
        if rows == []:
            return f'<div>No data provided.</div>'
        colors = ["#ff6b6b", "#4ecdc4", "#ffe66d", "#a55eea", "#feca57", "#ff9ff3"]
        total = sum(float(row[1]) for row in rows)
        gradient_stops = []
        legend_items = []
        cumulative_percentage = 0

        for i, (label, value) in enumerate(rows):
            percentage = (float(value) / total) * 100
            gradient_stops.append(f"{colors[i % len(colors)]} {cumulative_percentage}% {cumulative_percentage + percentage}%")
            legend_items.append(f'<div class="legend-item"><div class="legend-color" style="background: {colors[i % len(colors)]};"></div>{label} ({percentage:.2f}%)</div>')
            cumulative_percentage += percentage

        gradient = "conic-gradient(" + ", ".join(gradient_stops) + ")"
        pie_chart = f'<div class="pie-chart" style="background: {gradient};"></div>'
        legend = '<div class="legend">' + "".join(legend_items) + "</div>"

        return pie_chart + legend
    except Exception as e:
        return f'<div>Error creating chart, check table data!</div>'

def render_bar_chart(rows):
    try:
        if rows == []:
            return f'<div>No data provided.</div>'
        colors = ["#4ecdc4", "#ff6b6b", "#ffe66d", "#a55eea", "#feca57", "#ff9ff3"]
        max_value = max(float(row[1]) for row in rows)
        bars = []

        for i, (label, value) in enumerate(rows):
            bar_height = (float(value) / max_value) * 100
            bars.append(f'''
                <div class="bar-container">
                    <div class="bar" style="height: {bar_height}%; background: {colors[i % len(colors)]};"></div>
                    <div class="bar-label">{label}</div>
                </div>
            ''')

        bar_chart = f'''
            <div class="bar-chart">
                {"".join(bars)}
            </div>
        '''
        return bar_chart
    except Exception as e:
        return f'<div>Error creating chart, check table data!</div>'

def render_macro_generic(node: Macro) -> str:
    inner = parse_inline(node.content)
    return f'<div class="{html.escape(node.name)}">{inner}</div>'

def render(node: Node) -> str:
    if isinstance(node, Document):
        title = str(node.meta.get("title", ""))
        author = str(node.meta.get("author", ""))

        style = str(node.meta.get("style", "default")).strip() or "default"

        darkmode = str(node.meta.get("darkmode", "")).lower() in ("true", "1", "yes") # user feedback showed that not everyone agrees on "true"
        mode = "dark" if darkmode else "light"

        stylesheet_path = f"themes/{html.escape(style)}/{mode}.css"

        head = (
            f"<!-- Generated by annaScript, https://tk-dev-software.com/annascript/ -->\n"
            "<!DOCTYPE html>\n<html>\n  <head>\n"
            "    <meta charset='utf-8'>\n"
            "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
            f"    <title>{title}</title>\n"
            f"    <meta name='author' content='{author}'>\n"
            f"    <link rel='stylesheet' href='{stylesheet_path}'>\n"
            "  </head>"
        )

        body = "\n".join(render(ch) for ch in node.children)
        return f"{head}\n  <body>\n{body}\n  </body>\n</html>"


    if isinstance(node, Heading):
        return f"<h{node.level}>{parse_inline(node.text)}</h{node.level}>"

    if isinstance(node, Paragraph):
        txt = " ".join(line.strip() for line in node.lines)
        return f"<p>{parse_inline(txt)}</p>"

    if isinstance(node, CodeBlock):
        return f"<pre><code>{html.escape(node.code)}</code></pre>"

    if isinstance(node, ListItem):
        inner = parse_inline(node.text)
        children_html = "".join(render(ch) for ch in node.children)
        return f"<li>{inner}{children_html}</li>"


    if isinstance(node, UL):
        items_html = "".join(render(item) for item in node.items)
        return f"<ul>{items_html}</ul>"

    if isinstance(node, OL):
        items_html = "".join(render(item) for item in node.items)
        return f"<ol>{items_html}</ol>"


    if isinstance(node, Table):
        header_html = ""
        rows = node.rows[:]
        if len(rows) >= 2 and all(re.match(r'^:?-+:?$', c.replace(" ", "")) for c in rows[1]):
            header = rows[0]
            header_html = "<thead><tr>" + "".join(f"<th>{parse_inline(c)}</th>" for c in header) + "</tr></thead>"
            body_rows = rows[2:]
        else:
            body_rows = rows
        body_html = "<tbody>" + "".join("<tr>" + "".join(f"<td>{parse_inline(c)}</td>" for c in r) + "</tr>" for r in body_rows) + "</tbody>"
        return f"<table>{header_html}{body_html}</table>"

    if isinstance(node, Macro):
        fn = _macro_registry.get(node.name, render_macro_generic)
        return fn(node)

    if isinstance(node, Comment):
        return ""

    # fallback
    return ""
